### ISSUE TITLE
Dependency on Sequencer module

### ISSUE THREAD

**Issue by KristjanLaane** [napolitanod/Target-Recall#4]
When trying to use your module, throws:

```
target-recall.js:199 Uncaught (in promise) ReferenceError: Sequencer is not defined
[Detected 1 package: target-recall]
    at recall._ui (target-recall.js:199:5)
    at recall.target (target-recall.js:161:10)
    at async Function.target (target-recall.js:87:19)
```

Error disappears when also install Sequencer module and activate that. 

There is a way to add module dependencies in module.json, might be worth doing.

**Comment by napolitanod** [comment]
Sequencer is intended to be optional. I'll take a look to see why this is triggering. Thanks!

**Comment by napolitanod** [comment]
Ok, this should be fixed. Looking through the code I never actually implemented Sequencer as optional but that was my intention. Shouldn't throw an error anymore.
