### ISSUE TITLE
Targeting documentation

### ISSUE THREAD

**Issue by KristjanLaane** [napolitanod/Target-Recall#5]
Target Recall functionality does not work and Target Finder is not shown when manually clicking the button on the token HUD:
![image](https://user-images.githubusercontent.com/1708294/166231683-b41a9046-4578-4b0f-a858-5b7bf622e4f6.png)

After lots of experimentation I realized it was because targeting like this selects the token, and your module only works based on the attacker being the selected token.

Target Finder shows up nicely if i have the attacker token selected and then target using hover and shortcut key T. 

Would be great to document that somewhere.

In terms of ease of use, intuitively i expected the current combatant to always be the attacker from which the distance is calculated and i expected it to not matter which token is selected.

**Comment by napolitanod** [comment]
Yes, that makes sense. I missed that use case because I don't target that way. Let me see about switching it to active combatant.

**Comment by napolitanod** [comment]
On look at the code the targeting is done from the current combatant. I think the issue is that targeting the token from the HUD isn't also triggering the distance finder. I'll update it so this method of targeting also surfaces the distance finder. Thanks!

**Comment by KristjanLaane** [comment]
I tested the freshly baked version 1.1.1 and still the token has to be selected to show the Finder:
![hoverT](https://user-images.githubusercontent.com/1708294/166285696-37106013-0ec5-4105-b41b-285af3053116.gif)
(i am hovering the mouse over the token and pressing T to target)

**Comment by napolitanod** [comment]
Yes, I've not yet addressed this ticket yet - 1.1.1 has the fix for sequencer error. I have the code for this ticket likely complete but need to test it.

**Comment by napolitanod** [comment]
I had a bit of a delay completing this due to some race conditions but just pushed out 1.1.2 which should support targeting from the token HUD. Please give that a shot.

Thanks!

**Comment by KristjanLaane** [comment]
Yes, works perfectly now. Thank You!
